openapi: 3.0.1
info:
  title: OpenDSU communication APIs
  description: This a project to model OpenDSU communication systems using OpenAPI
    standard
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 1.0.0
servers:
  - url: https://localhost:8080
  - url: http://localhost:8080
tags:

  - name: APIHub APIs - Upload
    description: Upload and download files
    externalDocs:
      description: Find out more
      url: https://privatesky.xyz

paths:

  /files/upload/{folder}:
    post:
      tags:
        - APIHub APIs - Upload
      summary: Upload the contents of a file into the specified folder
      operationId: uploadFile
      parameters:
        - name: folder
          in: path
          description: The folder under which the file contents will be uploaded
          required: true
          schema:
            type: string
      requestBody:
        description: Body will contain the content of the file
        content:
          application/octet-stream: {}
      responses:
        "500":
          description: Invalid folder or I/O operation
        "200":
          description: Returns the path under which the file contents were saved
          content:
            application/json:
              schema:
                type: object
                properties:
                  path:
                    type: string

  /files/download/{filepath}:
    get:
      tags:
        - APIHub APIs - Upload
      summary: Download the contents of the file identified by the filepath
      operationId: downloadFile
      parameters:
        - name: filepath
          in: path
          description: The path of the file to download
          required: true
          schema:
            type: string
      responses:
        "404":
          description: I/O operation error or invalid file path
        "200":
          description: Return the content of the file
          content:
            image/png:
              schema:
                type: string
                format: binary

