openapi: 3.0.1
info:
  title: OpenDSU communication APIs
  description: This a project to model OpenDSU communication systems using OpenAPI
    standard
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 1.0.0
servers:
  - url: https://localhost:8080
  - url: http://localhost:8080
tags:

  - name: APIHub APIs - Service Work Replacement
    description: Provides operations using DSU workers by simulating Service Workers
    externalDocs:
      description: Find out more
      url: https://privatesky.xyz

paths:

  /iframe/{keySSI}/*:
    get:
      tags:
        - APIHub APIs - Service Work Replacement
      summary: Serves the requested content, identified by the appended path, using DSU workers
      parameters:
        - name: keySSI
          in: path
          description: keySSI in base58 encoding
          example: 29fgyfTQXJmJNni42zuJu3NXHgtUuXk3318NMMTrYKfj1gwAttt16rKq3vPCUjFV3KZeF9HJnaZnW4FnN7t7zBQFKjdXBwX
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Operation handled with success. Returns the content of the file
        "500":
          description: Invalid KeySSI
        "400":
          description: Worker resolver error
    put:
      tags:
        - APIHub APIs - Service Work Replacement
      summary: Serves the requested content, identified by the appended path, using DSU workers
      parameters:
        - name: keySSI
          in: path
          description: keySSI in base58 encoding
          example: 29fgyfTQXJmJNni42zuJu3NXHgtUuXk3318NMMTrYKfj1gwAttt16rKq3vPCUjFV3KZeF9HJnaZnW4FnN7t7zBQFKjdXBwX
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Operation handled with success. Returns the content of the file
        "500":
          description: Invalid KeySSI or invalid body
        "400":
          description: Worker resolver error
    post:
      tags:
        - APIHub APIs - Service Work Replacement
      summary: Serves the requested content, identified by the appended path, using DSU workers
      parameters:
        - name: keySSI
          in: path
          description: keySSI in base58 encoding
          example: 29fgyfTQXJmJNni42zuJu3NXHgtUuXk3318NMMTrYKfj1gwAttt16rKq3vPCUjFV3KZeF9HJnaZnW4FnN7t7zBQFKjdXBwX
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Operation handled with success. Returns the content of the file
        "500":
          description: Invalid KeySSI or invalid body
        "400":
          description: Worker resolver error


  /code/iframe/{keySSI}/*:
    get:
      tags:
        - APIHub APIs - Service Work Replacement
      summary: Serves the requested content, identified by the appended path, using DSU workers
      parameters:
        - name: keySSI
          in: path
          description: keySSI in base58 encoding
          example: 29fgyfTQXJmJNni42zuJu3NXHgtUuXk3318NMMTrYKfj1gwAttt16rKq3vPCUjFV3KZeF9HJnaZnW4FnN7t7zBQFKjdXBwX
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Operation handled with success. Returns the content of the file
        "500":
          description: Invalid KeySSI
        "400":
          description: Worker resolver error

    put:
      tags:
        - APIHub APIs - Service Work Replacement
      summary: Serves the requested content, identified by the appended path, using DSU workers
      parameters:
        - name: keySSI
          in: path
          description: keySSI in base58 encoding
          example: 29fgyfTQXJmJNni42zuJu3NXHgtUuXk3318NMMTrYKfj1gwAttt16rKq3vPCUjFV3KZeF9HJnaZnW4FnN7t7zBQFKjdXBwX
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Operation handled with success. Returns the content of the file
        "500":
          description: Invalid KeySSI or invalid body
        "400":
          description: Worker resolver error
    post:
      tags:
        - APIHub APIs - Service Work Replacement
      summary: Serves the requested content, identified by the appended path, using DSU workers
      parameters:
        - name: keySSI
          in: path
          description: keySSI in base58 encoding
          example: 29fgyfTQXJmJNni42zuJu3NXHgtUuXk3318NMMTrYKfj1gwAttt16rKq3vPCUjFV3KZeF9HJnaZnW4FnN7t7zBQFKjdXBwX
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Operation handled with success. Returns the content of the file
        "500":
          description: Invalid KeySSI or invalid body
        "400":
          description: Worker resolver error

